# PyTorch - AutoGrad

In [2]:
import torch

def _print(val):
    print(val,'\n')

In [7]:
x = torch.ones(2,2, requires_grad=True)
y = x + 2
_print(x.grad_fn) #first Tensor in graph has no grad_fn
_print(y.grad_fn)

None 




In [8]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.

In [9]:
_print(y)
out.backward()
_print(x.grad) #doutdx = (1/4)*6*3 = 4.5
_print(y.grad) #dydx  = 1
_print(z.grad)  #dzdy = 6y
_print(out.grad) #doutdz = 1/z.shape[0] = 1/4

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) 

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]]) 

None 

None 

None 



The derivative of a vector valued function z = f(y) is the __Jacobian Matrix.__ 
- ((dz1/dy1, ... , dz1/dyn)
- (dz2/dy1, ... , dz2/dyn)
- (       , ... ,        )
- ( dzn/dy1, ... , dzn/dyn))
 
 Autograd is a engine for computing a vector - Jacobian product. At each step in the the jacobian of the Function is multiplied by the Gradient-vector of the previous step.
 